In [2]:
import pandas as pd
import numpy as np

## I Dataset : CRX.Data 

Tasks:
1. In the dataset crx.data, name the columns as col1, col2..col16
2. Print the last 10 rows of data
3. Replace the ‘?’ with Not-a-Number
4. Comment on the datatype of variables
5. The col16 1. In the dataset crx.data, name the columns as col1, col2..col16 + and -, replace them ‘P’ and ‘N’ respectively
6. Find and display the number of variables of type ‘Object’

In [3]:
# Load the data
crx_data = pd.read_csv("data/crx.data", header=None)

In [4]:
crx_data.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

1. In the dataset crx.data, name the columns as col1, col2..col16

In [5]:
# Give names to  columns
columnnames = ["col" + str(s) for s in range(1,17)]

In [6]:
crx_data.columns = columnnames

In [7]:
crx_data.head()

col1   col2   col3 col4 col5 col6 col7  col8 col9 col10  col11 col12 col13  \
0    b  30.83  0.000    u    g    w    v  1.25    t     t      1     f     g   
1    a  58.67  4.460    u    g    q    h  3.04    t     t      6     f     g   
2    a  24.50  0.500    u    g    q    h  1.50    t     f      0     f     g   
3    b  27.83  1.540    u    g    w    v  3.75    t     t      5     t     g   
4    b  20.17  5.625    u    g    w    v  1.71    t     f      0     f     s   

   col14  col15 col16  
0  00202      0     +  
1  00043    560     +  
2  00280    824     +  
3  00100      3     +  
4  00120      0     +

2. Print the last 10 rows of data

In [8]:
crx_data.tail(10)

col1   col2    col3 col4 col5 col6 col7   col8 col9 col10  col11 col12  \
680    b  19.50   0.290    u    g    k    v  0.290    f     f      0     f   
681    b  27.83   1.000    y    p    d    h  3.000    f     f      0     f   
682    b  17.08   3.290    u    g    i    v  0.335    f     f      0     t   
683    b  36.42   0.750    y    p    d    v  0.585    f     f      0     f   
684    b  40.58   3.290    u    g    m    v  3.500    f     f      0     t   
685    b  21.08  10.085    y    p    e    h  1.250    f     f      0     f   
686    a  22.67   0.750    u    g    c    v  2.000    f     t      2     t   
687    a  25.25  13.500    y    p   ff   ff  2.000    f     t      1     t   
688    b  17.92   0.205    u    g   aa    v  0.040    f     f      0     f   
689    b  35.00   3.375    u    g    c    h  8.290    f     f      0     t   

    col13  col14  col15 col16  
680     g  00280    364     -  
681     g  00176    537     -  
682     g  00140      2     -  
683     g  00240      3     -  
684     s  00400      0     -  
685     g  00260      0     -  
686     g  00200    394     -  
687     g  00200      1     -  
688     g  00280    750     -  
689     g  00000      0     -

3. Replace the ‘?’ with Not-a-Number

In [9]:
# replace ? with nan
crx_data = crx_data.replace("?", np.nan)

4. Comment on the datatype of variables

In [10]:
crx_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    678 non-null    object 
 1   col2    678 non-null    object 
 2   col3    690 non-null    float64
 3   col4    684 non-null    object 
 4   col5    684 non-null    object 
 5   col6    681 non-null    object 
 6   col7    681 non-null    object 
 7   col8    690 non-null    float64
 8   col9    690 non-null    object 
 9   col10   690 non-null    object 
 10  col11   690 non-null    int64  
 11  col12   690 non-null    object 
 12  col13   690 non-null    object 
 13  col14   677 non-null    object 
 14  col15   690 non-null    int64  
 15  col16   690 non-null    object 
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB


5. The col16 1. In the dataset crx.data, name the columns as col1, col2..col16 + and -, replace them ‘P’ and ‘N’ respectively

In [11]:
# encode col16 values from + and - to P and N
crx_data["col16"]  = crx_data["col16"].map({"+":"P", "-":"N"})

In [12]:
crx_data["col16"]

0      P
1      P
2      P
3      P
4      P
      ..
685    N
686    N
687    N
688    N
689    N
Name: col16, Length: 690, dtype: object

6. Find and display the number of variables of type ‘Object’

In [13]:
cat_columns = [c for c in crx_data.columns if crx_data[c].dtypes == "O"]

In [14]:
crx_data[cat_columns].head()

col1   col2 col4 col5 col6 col7 col9 col10 col12 col13  col14 col16
0    b  30.83    u    g    w    v    t     t     f     g  00202     P
1    a  58.67    u    g    q    h    t     t     f     g  00043     P
2    a  24.50    u    g    q    h    t     f     f     g  00280     P
3    b  27.83    u    g    w    v    t     t     t     g  00100     P
4    b  20.17    u    g    w    v    t     f     f     s  00120     P

In [15]:
crx_data[cat_columns].columns

Index(['col1', 'col2', 'col4', 'col5', 'col6', 'col7', 'col9', 'col10',
       'col12', 'col13', 'col14', 'col16'],
      dtype='object')

## II Dataset: loan.csv

Tasks:
1. Display the mean of any two variables with continuous values
2. Print the number of discrete variables
3. Display the unique values of two variables with discrete values
4. Display the Month with most of loans issued date
5. Display the count of ‘Teacher’ who are ‘Owners’
6. Display the ‘Employment’ of customers who mostly ‘Rent’

In [19]:
loan_data = pd.read_csv("data/loan.csv")

In [20]:
loan_data.head()

customer_id  disbursed_amount  interest market    employment time_employed  \
0            0           23201.5   15.4840      C       Teacher     <=5 years   
1            1            7425.0   11.2032      B    Accountant     <=5 years   
2            2           11150.0    8.5100      A  Statistician     <=5 years   
3            3            7600.0    5.8656      A         Other     <=5 years   
4            4           31960.0   18.7392      E    Bus driver      >5 years   

  householder    income date_issued  target        loan_purpose  \
0        RENT   84600.0  2013-06-11       0  Debt consolidation   
1       OWNER  102000.0  2014-05-08       0        Car purchase   
2        RENT   69840.0  2013-10-26       0  Debt consolidation   
3        RENT  100386.0  2015-08-20       0  Debt consolidation   
4        RENT   95040.0  2014-07-22       0  Debt consolidation   

   number_open_accounts date_last_payment  number_credit_lines_12  
0                   4.0        2016-01-14                     NaN  
1                  13.0        2016-01-25                     NaN  
2                   8.0        2014-09-26                     NaN  
3                  20.0        2016-01-26                     NaN  
4                  14.0        2016-01-11                     NaN

In [21]:
loan_data.shape

(10000, 14)

1. Display the mean of any two variables with continuous values

In [22]:
loan_data["disbursed_amount"].unique()

array([23201.5 ,  7425.  , 11150.  , ...,  6279.  , 12894.75, 25584.  ])

In [23]:
loan_data["interest"].unique()

array([15.484 , 11.2032,  8.51  , ..., 12.9195, 11.2332, 11.0019])

In [24]:
loan_data[["disbursed_amount", "interest"]].mean()

disbursed_amount    14132.275500
interest               12.678819
dtype: float64

In [25]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   customer_id             10000 non-null  int64  
 1   disbursed_amount        10000 non-null  float64
 2   interest                10000 non-null  float64
 3   market                  10000 non-null  object 
 4   employment              9389 non-null   object 
 5   time_employed           9471 non-null   object 
 6   householder             10000 non-null  object 
 7   income                  10000 non-null  float64
 8   date_issued             10000 non-null  object 
 9   target                  10000 non-null  int64  
 10  loan_purpose            10000 non-null  object 
 11  number_open_accounts    10000 non-null  float64
 12  date_last_payment       10000 non-null  object 
 13  number_credit_lines_12  238 non-null    float64
dtypes: float64(5), int64(2), object(7)
memo

In [26]:
loan_data["income"] = loan_data["income"].astype("int64")
loan_data["number_open_accounts"] = loan_data["number_open_accounts"].astype("int64")

2. Print the number of discrete variables

In [27]:
discrete_columns = [c for c in loan_data.columns if loan_data[c].dtypes == "int64"]
print(discrete_columns)
print("The number of discrete variables :", len(discrete_columns))

['customer_id', 'income', 'target', 'number_open_accounts']
The number of discrete variables : 4


3. Display the unique values of two variables with discrete values

In [28]:
loan_data["number_open_accounts"].unique()

array([ 4, 13,  8, 20, 14,  5,  9, 18, 16, 17, 12, 15,  6, 10, 11,  7, 21,
       19, 26,  2, 22, 27, 23, 25, 24, 28,  3, 30, 41, 32, 33, 31, 29, 37,
       49, 34, 35, 38,  1, 36, 42, 47, 40, 44, 43], dtype=int64)

In [29]:
loan_data["income"].unique()

array([ 84600, 102000,  69840, ...,  26112, 228420, 133950], dtype=int64)

4. Display the Month with most of loans issued date

In [30]:
loan_data["date_issued_dt"] = pd.to_datetime(loan_data["date_issued"])

In [31]:
loan_data.head()

customer_id  disbursed_amount  interest market    employment time_employed  \
0            0           23201.5   15.4840      C       Teacher     <=5 years   
1            1            7425.0   11.2032      B    Accountant     <=5 years   
2            2           11150.0    8.5100      A  Statistician     <=5 years   
3            3            7600.0    5.8656      A         Other     <=5 years   
4            4           31960.0   18.7392      E    Bus driver      >5 years   

  householder  income date_issued  target        loan_purpose  \
0        RENT   84600  2013-06-11       0  Debt consolidation   
1       OWNER  102000  2014-05-08       0        Car purchase   
2        RENT   69840  2013-10-26       0  Debt consolidation   
3        RENT  100386  2015-08-20       0  Debt consolidation   
4        RENT   95040  2014-07-22       0  Debt consolidation   

   number_open_accounts date_last_payment  number_credit_lines_12  \
0                     4        2016-01-14                     NaN   
1                    13        2016-01-25                     NaN   
2                     8        2014-09-26                     NaN   
3                    20        2016-01-26                     NaN   
4                    14        2016-01-11                     NaN   

  date_issued_dt  
0     2013-06-11  
1     2014-05-08  
2     2013-10-26  
3     2015-08-20  
4     2014-07-22

In [32]:
loan_data["month"] = loan_data["date_issued_dt"].dt.month

In [33]:
max(loan_data.groupby("month").size())

1277

In [34]:
loan_data.groupby("month").size()

month
1      700
2      584
3      623
4      816
5      749
6      700
7     1066
8      852
9      734
10    1277
11    1017
12     882
dtype: int64

5. Display the count of ‘Teacher’ who are ‘Owners’

In [35]:
loan_data[["employment", "householder"]].value_counts()

employment          householder
Nurse               MORTGAGE       444
Accountant          MORTGAGE       440
Secretary           MORTGAGE       432
Taxi driver         MORTGAGE       429
Statistician        MORTGAGE       426
Other               MORTGAGE       425
Civil Servant       MORTGAGE       424
Teacher             MORTGAGE       421
Bus driver          MORTGAGE       418
Dentist             MORTGAGE       418
Software developer  MORTGAGE       417
Civil Servant       RENT           371
Teacher             RENT           371
Bus driver          RENT           360
Nurse               RENT           358
Dentist             RENT           355
Secretary           RENT           355
Other               RENT           353
Statistician        RENT           342
Accountant          RENT           322
Taxi driver         RENT           316
Software developer  RENT           315
Bus driver          OWNER           96
Accountant          OWNER           90
Civil Servant       OWNER       

In [36]:
count = 0
for c, d in zip(loan_data["employment"], loan_data["householder"]) :
    if c == 'Teacher' and d == "OWNER" :
        count+=1
print(count)

69


In [37]:
number_of_TO = loan_data.groupby(["employment","householder"]).get_group(("Teacher", "OWNER"))

In [38]:
number_of_TO[["customer_id", "employment","householder"]]

customer_id employment householder
71             71    Teacher       OWNER
85             85    Teacher       OWNER
171           171    Teacher       OWNER
672           672    Teacher       OWNER
1024         1024    Teacher       OWNER
...           ...        ...         ...
9154         9154    Teacher       OWNER
9172         9172    Teacher       OWNER
9433         9433    Teacher       OWNER
9684         9684    Teacher       OWNER
9769         9769    Teacher       OWNER

[69 rows x 3 columns]

In [39]:
len(number_of_TO)

69

6. Display the ‘Employment’ of customers who mostly ‘Rent’

In [40]:
number_of_rent = loan_data.groupby(["householder"]).get_group(("RENT"))

In [41]:
number_of_rent[["customer_id", "employment", "householder"]]

customer_id          employment householder
0               0             Teacher        RENT
2               2        Statistician        RENT
3               3               Other        RENT
4               4          Bus driver        RENT
6               6           Secretary        RENT
...           ...                 ...         ...
9991         9991  Software developer        RENT
9992         9992        Statistician        RENT
9994         9994          Accountant        RENT
9996         9996       Civil Servant        RENT
9998         9998          Bus driver        RENT

[4055 rows x 3 columns]

In [42]:
len(number_of_rent)

4055